// <auto-generated />
using System;
using EmptyProject_Work_01.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmptyProject_Work_01.Migrations
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20201102053340_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmptyProject_Work_01.Models.JobAdvertisement", b =>
                {
                    b.Property<int>("JobAdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobAdvertisementName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("OnlineJobSiteId");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("JobAdvertisementId");

                    b.HasIndex("OnlineJobSiteId");

                    b.ToTable("JobAdvertisements");
                });

            modelBuilder.Entity("EmptyProject_Work_01.Models.OnlineJobSite", b =>
                {
                    b.Property<int>("OnlineJobSiteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OnlineJobSiteName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Response");

                    b.Property<DateTime>("StartedJourney")
                        .HasColumnType("date");

                    b.Property<string>("Web");

                    b.HasKey("OnlineJobSiteId");

                    b.ToTable("OnlineJobSites");
                });

            modelBuilder.Entity("EmptyProject_Work_01.Models.RegisterApplicant", b =>
                {
                    b.Property<int>("RegisterApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("OnlineJobSiteId");

                    b.Property<string>("RegisterApplicantName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("RegisterApplicantId");

                    b.HasIndex("OnlineJobSiteId");

                    b.ToTable("RegisterApplicants");
                });

            modelBuilder.Entity("EmptyProject_Work_01.Models.JobAdvertisement", b =>
                {
                    b.HasOne("EmptyProject_Work_01.Models.OnlineJobSite", "OnlineJobSite")
                        .WithMany("JobAdvertisements")
                        .HasForeignKey("OnlineJobSiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EmptyProject_Work_01.Models.RegisterApplicant", b =>
                {
                    b.HasOne("EmptyProject_Work_01.Models.OnlineJobSite", "OnlineJobSite")
                        .WithMany("RegisterApplicants")
                        .HasForeignKey("OnlineJobSiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
